spring.application.name=springbootdemo
server.port=${PORT:8080}
#hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
#hibernate.connection.url= jdbc:mysql://localhost:3306/studentmangementdemo
#hibernate.connection.username=root
#hibernate.connection.password=Pass123
#hibernate.dialect= org.hibernate.dialect.MySQL8Dialect
#hibernate.show_sql=true
#hibernate.hbm2ddl.auto=update



hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url= jdbc:mysql://mysql-20d8e825-demodatabase1.k.aivencloud.com:17853/studentmanagementdb
hibernate.connection.username=${DB_USERNAME}
hibernate.connection.password=${DB_PASSWORD}
hibernate.dialect= org.hibernate.dialect.MySQL8Dialect
hibernate.show_sql=true
hibernate.hbm2ddl.auto=update